from flask import Blueprint, render_template, session, redirect, url_for, request, jsonify, send_file
from db import get_db
from datetime import datetime, date
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    PageBreak, Image as RLImage, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.pdfgen import canvas
import os
from collections import defaultdict
from decimal import Decimal

records_bp = Blueprint("records_bp", __name__)


def login_required():
    return "user_id" in session


# Custom page template with header and footer
class NumberedCanvas(canvas.Canvas):
    """Custom canvas for adding page numbers and headers/footers"""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []
        self.report_type = kwargs.get('report_type', 'milk')

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        """Add header, footer, and page numbers"""
        self.saveState()
        
        # Footer line
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(1)
        self.line(1.5*cm, 2*cm, A4[0] - 1.5*cm, 2*cm)
        
        # Page number
        self.setFont('Helvetica', 9)
        self.setFillColor(colors.HexColor("#718096"))
        page_num = len([s for s in self._saved_page_states if s == self.__dict__]) + 1
        self.drawRightString(A4[0] - 1.5*cm, 1.5*cm, f"Page {page_num} of {page_count}")
        
        # Footer text
        self.drawString(1.5*cm, 1.5*cm, "© 2026 CattleTrack Pro")
        self.drawCentredString(A4[0]/2, 1.5*cm, "Generated by CattleTrack Pro System")
        
        self.restoreState()


def create_milk_pdf(records, start_date, end_date, username):
    """Generate professional milk production PDF report"""
    
    os.makedirs("static/reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Milk_Report_{timestamp}.pdf"
    filepath = f"static/reports/{filename}"
    
    # Create document
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=1.5*cm,
        leftMargin=1.5*cm,
        topMargin=2.5*cm,
        bottomMargin=3*cm,
        title=f" Milk Report",
        author="CattleTrack Pro"
    )
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#667EEA'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    info_style = ParagraphStyle(
        'InfoStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=6
    )
    
    # Build story
    story = []
    
    # Header with logo placeholder
    story.append(Paragraph("🐄 CATTLETRACK PRO", title_style))
    story.append(Paragraph("Milk Production Report", subtitle_style))
    
    # Info box
    info_data = [
        ["Report Generated:", datetime.now().strftime("%B %d, %Y at %I:%M %p")],
        ["Generated By:", username],
        ["Report Period:", f"{start_date} to {end_date}" if start_date and end_date else "All Time"],
        ["Total Records:", str(len(records))]
    ]
    
    info_table = Table(info_data, colWidths=[4*cm, 12*cm])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F7FAFC')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2D3748')),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
    ]))
    
    story.append(info_table)
    story.append(Spacer(1, 20))
    
    # Summary statistics
    total_milk = sum(float(r['quantity']) for r in records)
    total_income = sum(float(r['income']) for r in records)
    avg_milk = total_milk / len(records) if records else 0
    avg_rate = sum(float(r['rate']) for r in records) / len(records) if records else 0
    
    story.append(Paragraph("Summary Statistics", heading_style))
    
    summary_data = [
        ["Metric", "Value"],
        ["Total Milk Produced", f"{total_milk:.2f} Liters"],
        ["Total Income Generated", f"Rs.{total_income:,.2f}"],
        ["Average Milk/Day", f"{avg_milk:.2f} Liters"],
        ["Average Rate", f"Rs.{avg_rate:.2f}/Liter"],
        ["Number of Records", str(len(records))]
    ]
    
    summary_table = Table(summary_data, colWidths=[8*cm, 8*cm])
    summary_table.setStyle(TableStyle([
        # Header row
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667EEA')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        
        # Data rows
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#2D3748')),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 1), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ALIGN', (0, 1), (0, -1), 'LEFT'),
        ('ALIGN', (1, 1), (1, -1), 'RIGHT'),
        
        # Borders and padding
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F7FAFC')]),
    ]))
    
    story.append(summary_table)
    story.append(Spacer(1, 25))
    
    # Detailed records
    story.append(Paragraph("Detailed Milk Records", heading_style))
    
    # Group records by cow
    records_by_cow = defaultdict(list)
    for record in records:
        records_by_cow[record['cow_name']].append(record)
    
    # Create table data
    table_data = [["Date", "Cow Name", "Milk (L)", "Rate (Rs./L)", "Income (Rs.)"]]
    
    for cow_name in sorted(records_by_cow.keys()):
        cow_records = sorted(records_by_cow[cow_name], key=lambda x: x['date'], reverse=True)
        
        for record in cow_records:
            table_data.append([
                record['date'].strftime("%d %b %Y") if isinstance(record['date'], date) else str(record['date']),
                record['cow_name'],
                f"{float(record['quantity']):.2f}",
                f"Rs.{float(record['rate']):.2f}",
                f"Rs.{float(record['income']):.2f}"
            ])
    
    # Create table with proper styling
    detail_table = Table(table_data, colWidths=[3*cm, 4*cm, 3*cm, 3*cm, 3.5*cm])
    detail_table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667EEA')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        
        # Data
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 1), (0, -1), 'CENTER'),  # Date
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),    # Cow name
        ('ALIGN', (2, 1), (-1, -1), 'RIGHT'),  # Numbers
        
        # Borders and styling
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F7FAFC')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    story.append(detail_table)
    
    # Add page break before next section if needed
    story.append(Spacer(1, 20))
    
    # Footer note
    footer_note = Paragraph(
        "<i>This report is computer generated and contains confidential information. "
        "For any queries, please contact: info@cattletrack.com | +1 (555) 123-4567</i>",
        ParagraphStyle('FooterNote', parent=styles['Normal'], fontSize=8, 
                      textColor=colors.HexColor('#718096'), alignment=TA_CENTER)
    )
    story.append(footer_note)
    
    # Build PDF
    doc.build(story, canvasmaker=lambda *args, **kwargs: NumberedCanvas(*args, report_type='milk', **kwargs))
    
    return filepath


def create_expense_pdf(records, start_date, end_date, username):
    """Generate professional expense PDF report"""
    
    os.makedirs("static/reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Expense_Report_{timestamp}.pdf"
    filepath = f"static/reports/{filename}"
    
    # Create document
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=1.5*cm,
        leftMargin=1.5*cm,
        topMargin=2.5*cm,
        bottomMargin=3*cm,
        title=f" Expense Report",
        author="CattleTrack Pro"
    )
    
    # Styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#48BB78'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    # Build story
    story = []
    
    # Header
    story.append(Paragraph("🐄 CATTLETRACK PRO", title_style))
    story.append(Paragraph("Expense Records Report", subtitle_style))
    
    # Info box
    info_data = [
        ["Report Generated:", datetime.now().strftime("%B %d, %Y at %I:%M %p")],
        ["Generated By:", username],
        ["Report Period:", f"{start_date} to {end_date}" if start_date and end_date else "All Time"],
        ["Total Records:", str(len(records))]
    ]
    
    info_table = Table(info_data, colWidths=[4*cm, 12*cm])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F0FFF4')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2D3748')),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
    ]))
    
    story.append(info_table)
    story.append(Spacer(1, 20))
    
    # Summary statistics
    total_expense = sum(float(r['amount']) for r in records)
    
    # Group by category
    by_category = defaultdict(float)
    for r in records:
        by_category[r['type']] += float(r['amount'])
    
    story.append(Paragraph("Expense Summary", heading_style))
    
    summary_data = [["Category", "Amount (Rs.)", "Percentage"]]
    for category in sorted(by_category.keys()):
        amount = by_category[category]
        percentage = (amount / total_expense * 100) if total_expense > 0 else 0
        summary_data.append([
            category,
            f"Rs.{amount:,.2f}",
            f"{percentage:.1f}%"
        ])
    
    summary_data.append(["TOTAL", f"Rs.{total_expense:,.2f}", "100%"])
    
    summary_table = Table(summary_data, colWidths=[6*cm, 5*cm, 5*cm])
    summary_table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#48BB78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        
        # Data rows
        ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -2), 10),
        ('ALIGN', (0, 1), (0, -2), 'LEFT'),
        ('ALIGN', (1, 1), (-1, -2), 'RIGHT'),
        
        # Total row
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#F0FFF4')),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, -1), (-1, -1), 11),
        
        # Borders
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#F7FAFC')]),
    ]))
    
    story.append(summary_table)
    story.append(Spacer(1, 25))
    
    # Detailed records
    story.append(Paragraph("Detailed Expense Records", heading_style))
    
    table_data = [["Date", "Expense Category", "Amount (Rs.)"]]
    
    for record in sorted(records, key=lambda x: x['date'], reverse=True):
        table_data.append([
            record['date'].strftime("%d %b %Y") if isinstance(record['date'], date) else str(record['date']),
            record['type'],
            f"Rs.{float(record['amount']):,.2f}"
        ])
    
    detail_table = Table(table_data, colWidths=[4*cm, 7*cm, 5*cm])
    detail_table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#48BB78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        
        # Data
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 1), (0, -1), 'CENTER'),
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),
        ('ALIGN', (2, 1), (2, -1), 'RIGHT'),
        
        # Styling
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F7FAFC')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    story.append(detail_table)
    story.append(Spacer(1, 20))
    
    # Footer note
    footer_note = Paragraph(
        "<i>This report is computer generated and contains confidential information. "
        "For any queries, please contact: info@cattletrack.com | +1 (555) 123-4567</i>",
        ParagraphStyle('FooterNote', parent=styles['Normal'], fontSize=8,
                      textColor=colors.HexColor('#718096'), alignment=TA_CENTER)
    )
    story.append(footer_note)
    
    # Build PDF
    doc.build(story, canvasmaker=lambda *args, **kwargs: NumberedCanvas(*args, report_type='expense', **kwargs))
    
    return filepath


@records_bp.route("/records")
def records():
    """Display records page with pagination"""
    if not login_required():
        return redirect(url_for("login_page"))

    user_id = session["user_id"]
    
    # Get pagination parameter (default 25)
    per_page = request.args.get('per_page', 25, type=int)
    if per_page not in [10, 25, 50, 100]:
        per_page = 25
    
    conn = get_db()
    cur = conn.cursor(dictionary=True)

    # -------- Milk Records --------
    cur.execute("""
        SELECT 
            mr.date,
            c.name AS cow_name,
            mr.milk_liters AS quantity,
            mr.rate,
            mr.income
        FROM milk_records mr
        JOIN cattle c ON mr.cattle_id = c.id
        WHERE mr.user_id = %s
        ORDER BY mr.date DESC
        LIMIT %s
    """, (user_id, per_page))
    milk_records = cur.fetchall()
    
    # Get total count
    cur.execute("""
        SELECT COUNT(*) as total
        FROM milk_records
        WHERE user_id = %s
    """, (user_id,))
    total_milk = cur.fetchone()['total']

    # -------- Expense Records --------
    cur.execute("""
        SELECT 
            date,
            category AS type,
            amount
        FROM expenses
        WHERE user_id = %s
        ORDER BY date DESC
        LIMIT %s
    """, (user_id, per_page))
    expense_records = cur.fetchall()
    
    # Get total count
    cur.execute("""
        SELECT COUNT(*) as total
        FROM expenses
        WHERE user_id = %s
    """, (user_id,))
    total_expenses = cur.fetchone()['total']

    cur.close()
    conn.close()

    return render_template(
        "records.html",
        milk_records=milk_records,
        expense_records=expense_records,
        username=session.get("full_name", "User"),
        per_page=per_page,
        total_milk=total_milk,
        total_expenses=total_expenses
    )


@records_bp.route("/api/records/generate-pdf", methods=["POST"])
def generate_pdf_report():
    """Generate PDF report based on filters"""
    if not login_required():
        return jsonify(success=False, error="Not authenticated"), 401
    
    user_id = session["user_id"]
    data = request.get_json()
    
    report_type = data.get('report_type', 'milk')
    start_date = data.get('start_date')
    end_date = data.get('end_date')
    
    conn = get_db()
    cur = conn.cursor(dictionary=True)
    
    try:
        if report_type == 'milk':
            # Build query
            if start_date and end_date:
                query = """
                    SELECT 
                        mr.date,
                        c.name AS cow_name,
                        mr.milk_liters AS quantity,
                        mr.rate,
                        mr.income
                    FROM milk_records mr
                    JOIN cattle c ON mr.cattle_id = c.id
                    WHERE mr.user_id = %s 
                    AND mr.date BETWEEN %s AND %s
                    ORDER BY mr.date DESC
                """
                params = (user_id, start_date, end_date)
            else:
                query = """
                    SELECT 
                        mr.date,
                        c.name AS cow_name,
                        mr.milk_liters AS quantity,
                        mr.rate,
                        mr.income
                    FROM milk_records mr
                    JOIN cattle c ON mr.cattle_id = c.id
                    WHERE mr.user_id = %s
                    ORDER BY mr.date DESC
                """
                params = (user_id,)
            
            cur.execute(query, params)
            records = cur.fetchall()
            
            if not records:
                return jsonify(success=False, error="No records found"), 404
            
            pdf_path = create_milk_pdf(
                records, 
                start_date or "All Time", 
                end_date or "All Time",
                session.get("full_name", "User")
            )
            
        else:  # expense
            if start_date and end_date:
                query = """
                    SELECT date, category AS type, amount
                    FROM expenses
                    WHERE user_id = %s 
                    AND date BETWEEN %s AND %s
                    ORDER BY date DESC
                """
                params = (user_id, start_date, end_date)
            else:
                query = """
                    SELECT date, category AS type, amount
                    FROM expenses
                    WHERE user_id = %s
                    ORDER BY date DESC
                """
                params = (user_id,)
            
            cur.execute(query, params)
            records = cur.fetchall()
            
            if not records:
                return jsonify(success=False, error="No records found"), 404
            
            pdf_path = create_expense_pdf(
                records,
                start_date or "All Time",
                end_date or "All Time",
                session.get("full_name", "User")
            )
        
        # Return file path for download
        return jsonify(
            success=True,
            file_path=f"/{pdf_path}",
            filename=os.path.basename(pdf_path)
        )
        
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return jsonify(success=False, error=str(e)), 500
    
    finally:
        cur.close()
        conn.close()


@records_bp.route("/api/records/load-more", methods=["POST"])
def load_more_records():
    """Load more records via AJAX"""
    if not login_required():
        return jsonify(success=False), 401
    
    user_id = session["user_id"]
    data = request.get_json()
    
    record_type = data.get('type', 'milk')
    offset = data.get('offset', 0)
    limit = data.get('limit', 25)
    
    conn = get_db()
    cur = conn.cursor(dictionary=True)
    
    try:
        if record_type == 'milk':
            cur.execute("""
                SELECT 
                    mr.date,
                    c.name AS cow_name,
                    mr.milk_liters AS quantity,
                    mr.rate,
                    mr.income
                FROM milk_records mr
                JOIN cattle c ON mr.cattle_id = c.id
                WHERE mr.user_id = %s
                ORDER BY mr.date DESC
                LIMIT %s OFFSET %s
            """, (user_id, limit, offset))
        else:
            cur.execute("""
                SELECT date, category AS type, amount
                FROM expenses
                WHERE user_id = %s
                ORDER BY date DESC
                LIMIT %s OFFSET %s
            """, (user_id, limit, offset))
        
        records = cur.fetchall()
        
        # Convert date objects to strings
        for record in records:
            if isinstance(record['date'], date):
                record['date'] = record['date'].strftime('%Y-%m-%d')
        
        return jsonify(success=True, records=records)
        
    except Exception as e:
        print(f"Error loading records: {e}")
        return jsonify(success=False, error=str(e)), 500
    
    finally:
        cur.close()
        conn.close()
